// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alipay: typeof import('./src/components/Alipay.vue')['default']
    BarChart: typeof import('./src/components/echart/BarChart.vue')['default']
    Button: typeof import('./src/components/HomePage/Button.vue')['default']
    Calender: typeof import('./src/components/echart/Calender.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Footer: typeof import('./src/components/HomePage/Footer.vue')['default']
    Header: typeof import('./src/components/HomePage/Header.vue')['default']
    Loading: typeof import('./src/components/HomePage/Loading.vue')['default']
    Logo: typeof import('./src/components/HomePage/Logo.vue')['default']
    NomalBar: typeof import('./src/components/echart/NomalBar.vue')['default']
    Page: typeof import('./src/components/HomePage/Page.vue')['default']
    PieChart: typeof import('./src/components/echart/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    STable: typeof import('./src/components/STable.vue')['default']
    Toast: typeof import('./src/components/HomePage/Toast.vue')['default']
    WordCloud: typeof import('./src/components/WordCloud.vue')['default']
  }
}
